# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3

repos:

- repo: local
  hooks:
    - id: generate-requirements-app
      name: Generate app requirements
      entry: poetry export --without-hashes -f requirements.txt -o requirements.txt --only app
      language: system
      types: [python]
      pass_filenames: false


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: '.bumpversion.cfg'
  - id: check-ast
    language_version: python3.11
  - id: fix-encoding-pragma

- repo: https://github.com/hadolint/hadolint
  rev: v2.8.0
  hooks:
    - id: hadolint
      args: [--ignore, DL3006, --ignore, SC2086]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
